-- Generated by roblox-gen v0.0.1.
-- ▼ Class definition 'Animal' ▼
local Animal = {}
Animal.__index = Animal
Animal.__tostring = function()
  return "Animal"
end
function Animal.constructor(age, name)
  local self = setmetatable({}, Animal)
  self.age = age
  self.name = name
  return self
end
function Animal:Get_Name()
  return self.name
end
-- ▲ Class definition 'Animal' ▲
print("Creating Animal...")
local x = Animal.constructor(3, "jeb")
local __0__ = x:Get_Name()
print(__0__)