-- Generated by roblox-gen v0.0.1.
-- ▼ Class definition 'Person' ▼
local Person = {}
Person.__index = Person
Person.__tostring = function()
  return "Person"
end
function Person.constructor(name, age)
  local self = setmetatable({}, Person)
  self.name = name
  self.age = age
  return self
end
function Person:say_name()
  print("I am " .. self.name)
end
-- ▲ Class definition 'Person' ▲
local p1 = Person.constructor("John", 36)
print(p1.name)
print(p1.age)